### ISSUE TITLE
Coordonnées Lambert 93

### ISSUE THREAD

**Issue by ghost** [GuillaumePressiat/finess_etalab#1]
En testant les coordonnées converties du système Lambert 93 vers le WGS84, les points étaient mal placés (dans le pacifique pour des établissements Alsaciens par exemple :-) ).

Il se peut qu'il y ai une erreur sur cette ligne

https://github.com/GuillaumePressiat/finess_etalab/blob/d034c5dbe5438966c6235c614312a0a066a81329/pgm/ajout_coordonnees_wgs84.R#L9

Je l'ai remplacée par celle ci, qui règle le problème

```r
  p == 'LAMBERT_93' ~ "+init=epsg:2154",
```

[EPSG 2164 est bien celui du Lambert 93](http://epsg.io/2154)

**Comment by GuillaumePressiat** [comment]
Bonjour,

Merci de ta remarque, j'ai également le problème en fait, mais je ne l'avais pas avec les anciennes versions de rgdal, avec lesquelles j'avais initialement rédigé le programme. Sinon je m'en serai rendu compte !

En regardant la formule proj4 indiquée [ici](http://magrit.cnrs.fr/docs/projection_list_fr.html), celle que j'utilisais semble correcte et les deux sont équivalentes théoriquement.
 
Malgré tout j'ai adapté en prenant ce que tu indiques car c'est bien plus simple.

Merci !
